### PR TITLE
remove jquery.com dependency

### PR DESCRIPTION
**Pull request by herrfeuer**
remove jquery.com source - wont work in hamnet.
add jquery.min.js to webserver filelist to get it served.
remove <IE8 support.

### CODE REVIEW

**Comment by hessu** [comment]
Thank you, merged! I'll put out a new version some time soon.

**Comment by hessu** [comment]
By the way, did you actually try to compile this code with the patches? ;)

**Comment by hessu** [comment]
Fixed the bugs (made it actually compile, and install...), and released in version 2.0.19.

**Comment by herrfeuer** [comment]
Thank you, builds ans runs well on Debian8/armv7l (Olimex).

**Pull request merged**
