### PR TITLE
Guard against null dereference when no workers are running

### PR DESCRIPTION
**Pull request by fkautz**

### CODE REVIEW

**Comment by PhirePhly** [comment]
I usually assume 0 is an int data type. I'd rather use NULL for checking pointer equivalency.

**Comment by fkautz** [comment]
I've updated the PR to use NULL instead of 0

**Comment by hessu** [comment]
Hmm, it logs a LOG_INFO message but does not actually guard or return from the function, was that intentional?

If workers_running > 0 && worker_threads == NULL, it's quite a critical corruption at that point, might make sense to log at LOG_CRIT level and abort() out.

**Comment by fkautz** [comment]
@hessu I've updated the patch to log at CRIT level and abort as recommended.

**Comment by hessu** [comment]
Thank you, merged!

**Pull request merged**
